apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-linggago
resources:
  - ../../base
  - namespace.yaml
  - cm-mcrcon.yaml
  - deployment.yaml
  - cm-server-properties
  - cm-user-jvm-args
secretGenerator:
  - name: mc-env
    envs:
      - mc-env.env
    type: Opaque
patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: linggago
      namespace: minecraft-linggago
  - path: patch-delete-minecraft-container.yaml
    target:
      name: all-the-mods-10
      namespace: minecraft-linggago
images: 
  - name: docker.io/chrisroth667/minecraft
    newName: docker.io/chrisroth667/linggago
    newTag: "v6.3"
