apiVersion: v1
kind: Secret
metadata:
  name: minecraft-gitops-secrets
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "..."
  TELEGRAM_CHAT_ID: "..."
  GITHUB_TOKEN: "..."
  CURSEFORGE_API_KEY: "..."
  GITHUB_USER: "..."