apiVersion: apps/v1
kind: Deployment
metadata:
  name: aof7
spec:
  template:
    spec:
      volumes:
        - name: commands
          configMap:
            name: minecraft-commands
            items:
              - key: commands.txt
                path: commands.txt
      containers:
        - name: aof7-ops
          image: image-registry.openshift-image-registry.svc:5000/$(NAMESPACE)/aof7-ops:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_DIR
              value: /data
            - name: CMDS_FILE
              value: /data/commands.txt
            # Wähle EINE Fabric-Backup-Mod:
            - name: BACKUP_URL
              value: "https://mediafilez.forgecdn.net/files/7151/898/SimpleBackups-1.20.1-3.1.18.jar"
            - name: BACKUP_JAR_NAME
              value: "SimpleBackups-1.20.1-3.1.18.jar.jar"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: commands
              mountPath: /data/commands.txt
              subPath: commands.txt
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 0
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
