apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-linggango

resources:
  - ../../base
  - cm-eula.yaml
  - namespace.yaml
  - cm-mcrcon.yaml
  - deployment.yaml
  - cm-server-properties.yaml
  - cm-user-jvm-args.yaml
  - cm-startserver.yaml
  - secret-curseforge.yaml

secretGenerator:
  - name: mc-env
    type: Opaque
    envs:
      - mc-env.env

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: linggango
  - path: patch-delete-minecraft-container.yaml
    target:
      name: all-the-mods-10

images:
  - name: docker.io/chrisroth667/minecraft
    newName: docker.io/chrisroth667/linggango
    newTag: "v6.43.3"
