kind: ConfigMap
apiVersion: v1
metadata:
  name: aof7-startserver
  namespace: minecraft-aof7
data:
  startserver.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    APP_DIR="${APP_DIR:-/opt/aof7}"
    DATA_DIR="${DATA_DIR:-/data}"
    JAR="${JAR:-serverstarter-2.4.0.jar}"

    # ---- RCON ---- (UNVERÄNDERT)
    RCON_ENABLE="${RCON_ENABLE:-true}"
    RCON_HOST="${RCON_HOST:-127.0.0.1}"
    RCON_PORT="${RCON_PORT:-25575}"
    RCON_PASSWORD="${RCON_PASSWORD:-mc321}"
    RCON_WAIT_SECS="${RCON_WAIT_SECS:-1800}"   # bis zu 30 Minuten warten
    RCON_POLL_INTERVAL="${RCON_POLL_INTERVAL:-5}"

    # ---- Advanced Backups (Fabric) ----
    AB_FILE_ID="${AB_FILE_ID:-4818556}"
    AB_FILE_NAME="${AB_FILE_NAME:-AdvancedBackups-fabric-1.20-3.2.1.jar}"
    AB_DIR1=$(( AB_FILE_ID / 1000 ))
    AB_DIR2=$(( AB_FILE_ID % 1000 ))
    ADVANCED_BACKUPS_URL="${ADVANCED_BACKUPS_URL:-https://mediafilez.forgecdn.net/files/${AB_DIR1}/${AB_DIR2}/${AB_FILE_NAME}}"

    # ---- nc / ncat detection ---- (UNVERÄNDERT)
    NC_BIN="${NC_BIN:-nc}"
    if ! command -v "${NC_BIN}" >/dev/null 2>&1; then
      if command -v ncat >/dev/null 2>&1; then
        NC_BIN="ncat"
      fi
    fi

    mkdir -p "${DATA_DIR}/overrides/mods" "${DATA_DIR}/mods" "${DATA_DIR}/config"

    # ---- Config-Overrides ----
    CONFIG_OVERRIDE_DIR="${CONFIG_OVERRIDE_DIR:-${DATA_DIR}/overrides/config}"
    CONFIG_DIR="${CONFIG_DIR:-${DATA_DIR}/config}"
    # force = überschreibt immer; fill = nur fehlende Dateien befüllen
    CONFIG_OVERRIDE_MODE="${CONFIG_OVERRIDE_MODE:-force}"

    apply_config_overrides() {
      local src="${CONFIG_OVERRIDE_DIR}" dst="${CONFIG_DIR}"
      [[ -d "$src" ]] || return 0
      mkdir -p "$dst"
      if [[ "${CONFIG_OVERRIDE_MODE}" == "fill" ]]; then
        ( cd "$src" && find . -type d -exec mkdir -p "$dst/{}" \; )
        ( cd "$src" && find . -type f -print0 | while IFS= read -r -d '' f; do
            [[ -f "$dst/$f" ]] || cp -f "$src/$f" "$dst/$f"
          done )
      else
        if command -v tar >/dev/null 2>&1; then
          tar -C "$src" -cf - . | tar -C "$dst" -xpf -
        else
          ( cd "$src" && find . -type d -exec mkdir -p "$dst/{}" \; )
          ( cd "$src" && find . -type f -print0 | xargs -0 -I{} cp -f "$src/{}" "$dst/{}" )
        fi
      fi
    }

    # --- AdvancedBackups: Staging in overrides + Platzieren in mods ---
    stage_advanced_backups() {
      local fname="${AB_FILE_NAME}" url="${ADVANCED_BACKUPS_URL}" src=""
      [[ -n "${fname}" ]] || return 0

      # Schon vorhanden?
      if [[ -f "${DATA_DIR}/overrides/mods/${fname}" ]]; then
        return 0
      fi

      # Quelle suchen
      if   [[ -f "${APP_DIR}/extras/${fname}" ]]; then src="${APP_DIR}/extras/${fname}"
      elif [[ -f "${DATA_DIR}/${fname}" ]]; then        src="${DATA_DIR}/${fname}"
      fi

      # ggf. downloaden
      if [[ -z "${src}" && -n "${url}" ]]; then
        echo "[AB] downloading ${fname} from ${url}"
        if ! curl -fsSL "${url}" -o "${DATA_DIR}/overrides/mods/${fname}"; then
          echo "[AB] WARN: download failed for ${fname} (continuing)"
          return 0
        fi
        return 0
      fi

      # aus Quelle nach overrides/mods spiegeln
      if [[ -n "${src}" ]]; then
        cp -f "${src}" "${DATA_DIR}/overrides/mods/${fname}" || true
      fi
    }

    place_advanced_backups() {
      local fname="${AB_FILE_NAME}" src=""
      [[ -n "${fname}" ]] || return 0

      if   [[ -f "${DATA_DIR}/overrides/mods/${fname}" ]]; then src="${DATA_DIR}/overrides/mods/${fname}"
      elif [[ -f "${APP_DIR}/extras/${fname}" ]]; then          src="${APP_DIR}/extras/${fname}"
      elif [[ -f "${DATA_DIR}/${fname}" ]]; then                src="${DATA_DIR}/${fname}"
      fi

      if [[ -n "${src}" ]]; then
        mkdir -p "${DATA_DIR}/mods"
        cp -f "${src}" "${DATA_DIR}/mods/${fname}" || true
      fi
    }

    # =======================
    # EULA (UNVERÄNDERT)
    # =======================
    if [ ! -f eula.txt ] || ! grep -q 'eula=true' eula.txt; then
      if [ "${EULA:-}" = "TRUE" ] || [ "${EULA:-}" = "true" ]; then
        {
          echo "# By changing the setting below to TRUE you are indicating your agreement to the EULA (https://aka.ms/MinecraftEULA)."
          echo "# $(date -u)"
          echo "eula=true"
        } > eula.txt
        echo "[init] EULA accepted via ENV"
      else
        echo "[init] EULA not accepted. Setze ENV EULA=true oder lege /data/eula.txt mit 'eula=true' an."
        exit 3
      fi
    fi

    # 1) ServerStarter JAR bereitstellen (UNVERÄNDERT)
    cd "${DATA_DIR}"
    if [[ ! -f "${JAR}" ]]; then
      echo "[SS] fetching ${JAR}"
      curl -fsSL -o "${JAR}" "https://github.com/TeamAOF/ServerStarter/releases/download/v2.4.0/${JAR}"
    fi

    # 2) AdvancedBackups einmal in overrides/mods primen (falls noch nicht vorhanden)
    if [[ ! -f "${DATA_DIR}/overrides/mods/${AB_FILE_NAME}" ]]; then
      stage_advanced_backups || true
    fi

    # --> NEU: Config-Overrides VOR dem Start anwenden
    apply_config_overrides

    # 3) ServerStarter starten (UNVERÄNDERT)
    echo "[SS] starting ServerStarter ..."
    java -jar "${JAR}" &
    SERVER_PID=$!

    # 4) Frühstart-Fenster: Mod & Configs hartnäckig anwenden, bis RCON erreichbar oder Timeout
    (
      sleep 2
      end_time=$(( $(date +%s) + RCON_WAIT_SECS ))
      while [[ $(date +%s) -lt ${end_time} ]]; do
        place_advanced_backups
        apply_config_overrides
        if command -v "${NC_BIN}" >/dev/null 2>&1 && ${NC_BIN} -z "${RCON_HOST}" "${RCON_PORT}" 2>/dev/null; then
          break
        fi
        sleep 2
      done
    ) &

    # 5) Nach RCON-Start commands.txt schießen (UNVERÄNDERT)
    if [[ "${RCON_ENABLE}" == "true" && -s "${DATA_DIR}/commands.txt" ]]; then
      echo "[RCON] waiting for ${RCON_HOST}:${RCON_PORT} (timeout ${RCON_WAIT_SECS}s) ..."
      waited=0
      until command -v "${NC_BIN}" >/dev/null 2>&1 && ${NC_BIN} -z "${RCON_HOST}" "${RCON_PORT}" 2>/dev/null; do
        sleep "${RCON_POLL_INTERVAL}"
        waited=$(( waited + RCON_POLL_INTERVAL ))
        if [[ "${waited}" -ge "${RCON_WAIT_SECS}" ]]; then
          echo "[RCON] timeout (${RCON_WAIT_SECS}s) – skip commands"
          break
        fi
      done

      if command -v "${NC_BIN}" >/dev/null 2>&1 && ${NC_BIN} -z "${RCON_HOST}" "${RCON_PORT}" 2>/dev/null; then
        sleep 3
        echo "[RCON] sending commands from commands.txt"
        sed -e 's#^/##' -e '/^\s*#/d' -e '/^\s*$/d' "${DATA_DIR}/commands.txt" | \
          /usr/local/bin/mcrcon -H "${RCON_HOST}" -P "${RCON_PORT}" -p "${RCON_PASSWORD}" -s || true
      fi
    fi

    # 6) Auf Server warten (UNVERÄNDERT)
    wait "${SERVER_PID}"

