kind: ConfigMap
apiVersion: v1
metadata:
  name: aof7-startserver
  namespace: minecraft-aof7
data:
  startserver.sh: |
    #!/usr/bin/env bash
    set -euo pipefail
    
    APP_DIR="${APP_DIR:-/opt/aof7}"
    DATA_DIR="${DATA_DIR:-/data}"
    JAR="${JAR:-serverstarter-2.4.0.jar}"
    
    # --- RCON (ENV-Defaults) ---
    RCON_ENABLE="${RCON_ENABLE:-true}"
    RCON_PORT="${RCON_PORT:-25575}"
    RCON_PASSWORD="${RCON_PASSWORD:-mc321}"
    
    # --- SimpleBackups (feste Version aus CurseForge) ---
    SB_FILE_ID="${SB_FILE_ID:-7151898}"
    SB_FILE_NAME="${SB_FILE_NAME:-SimpleBackups-1.20.1-3.1.18.jar}"
    DIR1=$(( SB_FILE_ID / 1000 ))
    DIR2=$(( SB_FILE_ID % 1000 ))
    SIMPLEBACKUPS_URL="https://mediafilez.forgecdn.net/files/${DIR1}/${DIR2}/${SB_FILE_NAME}"
    
    mkdir -p "${DATA_DIR}/overrides/mods" "${DATA_DIR}/mods" "${DATA_DIR}/config"
    
    # 1) EULA separat ablegen (schreibbar)
    echo "eula=true" > "${DATA_DIR}/eula.txt"
    
    # 2) server.properties NUR LESEN (falls gemountet)
    PROP_FILE="${DATA_DIR}/server.properties"
    get_prop() {
      local key="$1"
      [[ -r "${PROP_FILE}" ]] || return 1
      local line
      line="$(grep -E "^[[:space:]]*${key}=" "${PROP_FILE}" | tail -n1 || true)"
      [[ -n "${line}" ]] || return 1
      printf '%s\n' "${line#*=}" | tr -d '\r'
      return 0
    }
    if [[ -r "${PROP_FILE}" ]]; then
      if v="$(get_prop 'rcon.port' || true)"; then RCON_PORT="$v"; fi
      if v="$(get_prop 'rcon.password' || true)"; then RCON_PASSWORD="$v"; fi
    fi
    
    # 3) SimpleBackups in overrides/mods legen (überlebt Sync des ServerStarter)
    echo "Fetching SimpleBackups from ${SIMPLEBACKUPS_URL}"
    curl -fsSL "${SIMPLEBACKUPS_URL}" -o "${DATA_DIR}/overrides/mods/${SB_FILE_NAME}"
    
    # 4) ServerStarter bereitstellen
    cd "${DATA_DIR}"
    if [[ ! -f "${JAR}" ]]; then
      curl -fsSL -o "${JAR}" "https://github.com/TeamAOF/ServerStarter/releases/download/v2.4.0/${JAR}"
    fi
    
    # 5) ServerStarter starten
    java -jar "${JAR}" &
    SERVER_PID=$!
    
    # 6) RCON-Commands: **GENAU** wie zuvor (nur ENV-Flag steuert, keine Dateiänderung)
    if [[ "${RCON_ENABLE}" == "true" && -s "${DATA_DIR}/commands.txt" ]]; then
      echo "Waiting for RCON on 127.0.0.1:${RCON_PORT} ..."
      for _ in {1..180}; do
        if nc -z 127.0.0.1 "${RCON_PORT}" 2>/dev/null; then
          # führende Slashes entfernen (RCON erwartet i.d.R. ohne /)
          sed 's#^/##' "${DATA_DIR}/commands.txt" | \
            /usr/local/bin/mcrcon -H 127.0.0.1 -P "${RCON_PORT}" -p "${RCON_PASSWORD}" -s || true
          break
        fi
        sleep 2
      done
    fi
    
    wait "${SERVER_PID}"
    
