apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc-world.yaml
  - pvc-backup.yaml
  - pvc-overrides.yaml
  - serviceaccount.yaml
  - secret-mcrcon.yaml
  - service.yaml
  - deployment.yaml
