# apps/aof7-sidecar-build.yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: aof7-ops
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: aof7-ops
spec:
  source:
    type: Git
    git:
      uri: https://github.com/FullMetal667/minecraft-gitops-aof7.git
      ref: main
    contextDir: build/docker/sidecar
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: aof7-ops:latest
  triggers:
    - type: Git
    - type: ImageChange
    - type: ConfigChange

