apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: minecraft-image-build
labels:
  app: minecraft
parameters:
  - name: MOD_NAME
    description: Kurzname des Modpacks (z.B. aof7, atm10)
    required: true
  - name: IMAGE_TAG
    description: Version/Tag des Images (z.B. 2.5.3 oder 5.0)
    required: true

  - name: GIT_URL
    description: Git-Repo URL mit dem Dockerfile
    required: true
  - name: GIT_REVISION
    description: Git-Branch/Tag
    value: main
  - name: CONTEXT_DIR
    description: Pfad zum Dockerfile im Repo
    value: build/docker

  - name: FILE_ID
    description: CurseForge File-ID des Serverpacks
    required: true
  - name: ZIP
    description: Name der ZIP-Datei des Serverpacks (z.B. ServerFiles-5.0.zip)
    required: true
  - name: DIR
    description: Verzeichnisname nach dem Entpacken (z.B. ServerFiles-5.0)
    required: true

  - name: DOCKER_REPO
    description: Docker Repo (ohne Image-Name)
    value: docker.io/chrisroth667

  - name: WEBHOOK_SECRET
    description: Secret für GitHub Webhook
    value: set-a-random-secret

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: github-webhook-secret
  type: Opaque
  stringData:
    WebHookSecretKey: "${WEBHOOK_SECRET}"

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: "${MOD_NAME}-${IMAGE_TAG}"
    labels:
      app: minecraft
      modpack: "${MOD_NAME}"
      version: "${IMAGE_TAG}"
  spec:
    source:
      type: Git
      git:
        uri: "${GIT_URL}"
        ref: "${GIT_REVISION}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
        buildArgs:
          - name: FILE_ID
            value: "${FILE_ID}"
          - name: ZIP
            value: "${ZIP}"
          - name: DIR
            value: "${DIR}"
        # falls du ein eigenes Dockerfile-Namen hast, hier setzen
        dockerfilePath: Dockerfile.atm10
    output:
      to:
        kind: DockerImage
        name: "${DOCKER_REPO}/${MOD_NAME}:${IMAGE_TAG}"
      pushSecret:
        name: dockerhub-push
    triggers:
      - type: GitHub
        github:
          secretReference:
            name: github-webhook-secret
      - type: ConfigChange

