apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minecraft
  namespace: openshift-gitops
spec:
  description: Project for minecraft-servers
  sourceRepos:
    - https://github.com/FullMetal667/minecraft-gitops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: 'minecraft-*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

