apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minecraft
  namespace: openshift-gitops
spec:
  description: Project for minecraft aof7
  sourceRepos:
    - https://github.com/FullMetal667/minecraft.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: minecraft-aof7
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

