apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-atm10
resources:
- ../../base

patches:
  - path: patch-env.yaml
    target:
      kind: Secret
      name: mc-env
      namespace: minecraft-atm10
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: all-the-mods-10
      namespace: minecraft-atm10
