apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-the-mods-10
  namespace: minecraft-atm10
spec:
  template:
    spec:
      containers:
      - name: minecraft
        resources:
          requests:
            memory: "8Gi"
          limits:
            memory: "14Gi"
