apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-sb4
resources:
  - ../../base
  - namespace.yaml
  - cm-mcrcon.yaml
  - cm-server-properties.yaml
  - cm-user-jvm-args.yaml
  - cm-startserver.yaml
  - deployment.yaml
secretGenerator:
  - name: mc-env
    envs:
      - mc-env.env
    type: Opaque
patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: ftb-stone-blocks-4
      namespace: minecraft-sb4
  - path: patch-delete-minecraft-container.yaml
    target:
      name: ftb-stone-blocks-4
      namespace: minecraft-sb4
images: 
  - name: docker.io/chrisroth667/minecraft
    newName: docker.io/chrisroth667/sb4
    newTag: "1.11.0"